# Generated by Django 3.2.13 on 2022-06-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_game_user_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="x_coordinate",
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="move",
            name="y_coordinate",
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
