# Generated by Django 3.2.13 on 2022-06-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='user_ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
